// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToolsApi.Data;

#nullable disable

namespace ToolsApi.Data.Migrations
{
    [DbContext(typeof(ToolsApiDbContext))]
    [Migration("20260209074924_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ToolsApi.Data.Models.ConnectionEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<ushort>("MimeType")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("Objective")
                        .HasColumnType("smallint unsigned");

                    b.Property<ulong>("Offset")
                        .HasColumnType("bigint unsigned");

                    b.Property<byte[]>("TransferId")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("varbinary(18)");

                    b.HasKey("Id");

                    b.HasIndex("TransferId")
                        .IsUnique();

                    b.ToTable("ConnectionEvents");
                });

            modelBuilder.Entity("ToolsApi.Data.Models.UserNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("WhatsAppNumber")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("WhatsAppNumber")
                        .IsUnique();

                    b.ToTable("UserNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
